universe = vanilla

executable = MAG_checkm.sh

#REQUIREMENTS:

Requirements = (OpSys == "LINUX") && (OpSysMajorVer == 9) && (Target.HasCHTCStaging == true)

transfer_input_files = PROG_instl/hmmer-3.4.tar.gz, \
                       PROG_instl/Prodigal-2.6.3.tar.gz, \
                       PROG_instl/pplacer-linux-v1.1.alpha19.zip, \    
                       PROG_instl/checkm_data_2015_01_16.tar.gz, \                       
                       PROG_instl/OS9/python-3.10.12.tar.gz, \
                       PROG_instl/OS9/python-3.10.12-packages.tar.gz

should_transfer_files = YES
when_to_transfer_output = ON_EXIT


log = MAG_checkm.log
error = MAG_checkm.error
output = MAG_checkm.out

request_memory = 100GB
request_disk = 100GB
request_cpus = 4