universe = docker

docker_image = staphb/prokka:1.14.6

executable = MAG_prokka.sh

#REQUIREMENTS:

Requirements = (OpSys == "LINUX") && (OpSysMajorVer == 9) && (Target.HasCHTCStaging == true)

transfer_input_files = PROG_instl/python-3.8.tar.gz, \
                       PROG_instl/python-3.8-packages.tar.gz, \
                       PROG_instl/run_prokka.py

should_transfer_files = YES
when_to_transfer_output = ON_EXIT


log = MAG_prokka.log
error = MAG_prokka.error
output = MAG_prokka.out

request_memory = 100GB
request_disk = 100GB
request_cpus = 4

queue