universe = vanilla

executable = MAG_drep.sh

#REQUIREMENTS:

Requirements = (OpSys == "LINUX") && (OpSysMajorVer == 9) && (Target.HasCHTCStaging == true)

transfer_input_files = PROG_instl/hmmer-3.4.tar.gz, \
                       PROG_instl/Prodigal-2.6.3.tar.gz, \
                       PROG_instl/pplacer-linux-v1.1.alpha19.zip, \    
                       PROG_instl/checkm_data_2015_01_16.tar.gz, \     
                       PROG_instl/mash-Linux64-v2.3.tar.gz, \     
                       PROG_instl/MUMmer-3.23.tar.gz, \ 
                       PROG_instl/OS9/FastANI-1.34.tar.gz, \
                       PROG_instl/OS9/gsl-2.8.tar.gz, \                       
                       PROG_instl/ANIcalculator_v1.tar.gz, \
                       PROG_instl/OS9/python-3.10.12.tar.gz, \
                       PROG_instl/OS9/python-3.10.12-packages.tar.gz

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

log = MAG_drep.log
error = MAG_drep.error
output = MAG_drep.out

request_memory = 100GB
request_disk = 100GB
request_cpus = 8

queue